<?= $this->partial('/common/header.phtml', $this) ?>
<?php foreach ($this->news_array as $news) { ?>
<h1><?= $news->id ?>.<a href="<?= $this->escape($news->url) ?>" target="_blank" rel="nofollow"><?= $this->escape(urldecode($news->url)) ?></a>(<?= $news->diff_count ?>)</h1>
<table class="table">
    <tr>
        <td>時間</td>
        <td>欄位</td>
        <td>變化</td>
    </tr>
    <?php $old_values = array(); ?>
    <?php foreach ($news->diffs as $diff) { ?>
    <tr>
        <td><a href="/index/log/<?= $news->id ?>/<?= $diff->time ?>"><?= date('c', $diff->time) ?></a></td>
        <td><?= $diff->column ? '內容' : '標題' ?>修改</td>
        <?php if (strlen($diff->diff) < 5) { ?>
        <td><?= $diff->diff ?></td>
        <?php } else { ?>
        <?php $raw = NewsRaw::find(array($diff->news_id, $diff->time)) ; ?>
        <td><?= $raw->getInfo()->title ?></td>
        <?php } ?>
    </tr>
    <?php } ?>
</table>
<?php } ?>
<?= $this->partial('/common/footer.phtml', $this) ?>
