<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?= $this->escape($this->title) ?>NewsDiff</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/bootstrap.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/css/bootstrap.css">
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="/">NewsDiff</a>
        <ul class="nav">
            <li>
            <a href="/">首頁</a>
            </li>
            <?php foreach (News::getSources() as $id => $name) { ?>
            <li>
            <a href="/index/source/<?= $id ?>"><?= $this->escape($name) ?></a>
            </li>
            <?php } ?>
        </ul>
        <form class="navbar-search pull-left" method="get" action="/index/search">
            <input type="text" class="search-query" name="q" placeholder="請輸入新聞連結">
        </form>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
